#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

hostname > /usr/local/apache2/htdocs/index.html
hostname -i >> /usr/local/apache2/htdocs/index.html

exec httpd -DFOREGROUND
