version: '2'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - ./certs:/certs
      - var_images:/var/lib/registry
      - ./auth/htpasswd:/auth
    ports:
      - "443:5000"
    environment: 
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.uft.edu.br.crt
      REGISTRY_HTTP_TLS_KEY: /certs/docker.uft.edu.br.key
      
      REGISTRY_AUTHY: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth
    extra_hosts:
      - "docker.uft.edu.br:172.16.8.188"
volumes:
  var_images:
#ip da maquina local
