logLevel="DEBUG"
debug=true

[web]
address=":8080"

[docker]
endpoint="unix://var/run/docker.sock"
watch=true
#swarmmode=true
domain="localhost"

[entryPoints]
   [entryPoints.http]
   address = ":80"
    [entryPoints.bar]
    address = ":8080"

[api]
  entryPoint = "bar"
dashboard = true
[ping]
  entryPoint = "bar"
[rest]
  entryPoint = "bar"
